name: Test deployment

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: docs

      - name: Install dependencies
        working-directory: docs
        run: yarn install --frozen-lockfile
      - name: Test build website
        working-directory: docs
        run: yarn build
